### ISSUE TITLE
Hide IP Address On Join Events

### ISSUE THREAD

**Issue by IstalriSkolir** [YiitWT/discordreporter#2]
When the server posts a player join event to a Discord server, it posts that players IP address with the details. Is it possible to have it post a join event with all the default details except the players IP address?

**Comment by yiitxyz** [comment]
Started working on. Im so sorry i didn't know how to use github I'm just seeing these :'(

**Comment by IstalriSkolir** [comment]
No worries dude! Appreciate you answering, thanks for letting me know!

**Comment by yiitxyz** [comment]
Fixed, releasing the new version.
